version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: careerForgeDB
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p12345 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_DATABASE=careerForgeDB
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    command: ./docker-entrypoint.sh

  react:
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: always
  nodejs:
    build:
      context: ./node-server
    environment:
      - OPENAI_API_KEY=${NODE_API_TOKEN}
    ports:
      - "3001:3001"
    dns: # Add this section
      - 8.8.8.8
      - 8.8.4.4
    restart: always
volumes:
  db_data:
