version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: careerForgeDB
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -p${DB_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 30
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: ${BACKEND_IMAGE}:${TAG}
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network
    restart: unless-stopped

  react:
    image: ${FRONTEND_IMAGE}:${TAG}
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

  nodejs:
    image: ${NODE_IMAGE}:${TAG}
    environment:
      - OPENAI_API_KEY=${NODE_API_TOKEN}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
