name: Run Laravel Tests with MySQL

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, mysql, zip, gd

      - name: Install Composer Dependencies
        run: |
          cd backend
          composer install --no-interaction --prefer-dist

      - name: Set up Environment File
        run: |
          cd backend
          cp .env.example .env
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=testdb" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=1234" >> .env
          php artisan key:generate
          php artisan jwt:secret
          php artisan config:clear

      - name: Run Tests
        run: |
          cd backend
          php artisan migrate:fresh --env=testing
          php artisan test
