name: Staging Tests

on:
  pull_request:
    branches: [staging]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, mysql, zip, gd

      - name: Install Composer dependencies
        run: |
          cd backend
          composer install --no-interaction --prefer-dist

      - name: Setup test environment
        run: |
          cd backend
          # Create .env file from example
          cp .env.example .env.testing
          # Set testing-specific values
          echo "APP_ENV=testing" > .env.testing
          echo "DB_CONNECTION=sqlite" >> .env.testing
          echo "DB_DATABASE=:memory:" >> .env.testing
          # Use .env.testing as the main .env
          cp .env.testing .env
          php artisan key:generate
          php artisan jwt:secret
          php artisan config:clear

      - name: Run migrations and tests
        run: |
          cd backend
          php artisan migrate:fresh
          php artisan test
